version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-tracker-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/tasktracker?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - task-tracker-network

  mongodb:
    image: mongo:latest
    container_name: task-tracker-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tasktracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-tracker-network

networks:
  task-tracker-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
